performance-rule-name:
  name-list: 
    fgc:
      - pps-N3-ul
      - pps-N3-dl
      - pps-N6-ul
      - pps-N6-dl
      - throughput-N3-ul
      - throughput-N3-dl
      - throughput-N6-ul
      - throughput-N6-dl    
    mec:
      - throughput-n3-ul
      - throughput-n3-dl
      - throughput-n6-ul
      - throughput-n6-dl    
      - throughput-n9-ul
      - throughput-n9-dl    
    ric:
      - accessibility-drbAccessibility5qi
      - accessibility-rrcConnSetupSR
      - retainability-drbRetain5qi
      - mobility-granHoSR
      - energySaving-eeMnDv
      - utilization-pduSesMeanNbr
      - utilization-vruProcessor
      - utilization-vruMemory
      - utilization-vruDisk
      - utilization-pduSesMaxNbr
      - integrity-dlDelayNrSNw
      - integrity-ulDelayNrSNw
      - integrity-dlUeTputSNw
      - integrity-ulUeTputSNw