#======================================================================================================================#
# 自定義參數
#======================================================================================================================#
solaris:
  #====================================================================================================================#
  # 自定義：Server Connection Configuration
  #====================================================================================================================#
  server:
    k8s:
      http: 
        url: ${K8S_URL}
    fgc:
      http:
        url: ${FGC_URL}
    mec:
      http:
        url: ${MEC_URL}
    ric:
      http:
        url: ${RIC_URL}
    open-daylight:
      http:
        host: ${ODL_HOST}
        port: ${ODL_PORT}
      openflow:
        vlan-match: ${OPENFLOW_VLAN_MATCH:false}
#======================================================================================================================#
# Spring
#======================================================================================================================#
spring:
  #====================================================================================================================#
  # Data Source (目前這個配置不使用，保留作為標準範本)
  #====================================================================================================================#  
  datasource:    
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    #==================================================================================================================#
    # Connection Pool - Hikari
    #==================================================================================================================#  
    hikari:
      minimum-idle: 30                        # 預設值 10，當 health check 時，在 connection-timeout 時間內，會一個接一個測試連線 
      maximum-pool-size: 100                  # 預設值 10
  #====================================================================================================================#
  # RabbitMQ 
  #====================================================================================================================#  
  rabbitmq:   
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
  #====================================================================================================================#
  # Mail
  #====================================================================================================================#
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    