package solaris.nfm.model.resource.appgroup;

public class AppGroupTestJson {
	public static String createGroupString_repair = "{\r\n"
			+ "    \"content\": {\r\n"
			+ "        \"id\": \"5cc95b20-e8f7-451d-bb96-0a4e44a24733\"\r\n"
			+ "    },\r\n"
			+ "    \"error_code\": \"00000\",\r\n"
			+ "    \"error_string\": \"success\"\r\n}" ;
	public static String createGroupString_ems = "{\r\n"
			+ "    \"content\": {\r\n"
			+ "        \"id\": \"6fbb1016-82b7-4f54-b60c-88b27dd9b422\"\r\n"
			+ "    },\r\n"
			+ "    \"error_code\": \"00000\",\r\n"
			+ "    \"error_string\": \"success\"\r\n}" ;
	public static String createGroupString_bim_viewer = "{\r\n"
			+ "    \"content\": {\r\n"
			+ "        \"id\": \"9482f447-b6ed-46ee-9268-54b70812196f\"\r\n"
			+ "    },\r\n"
			+ "    \"error_code\": \"00000\",\r\n"
			+ "    \"error_string\": \"success\"\r\n}" ;
	public static String createGroupString_postgres = "{\r\n"
			+ "    \"content\": {\r\n"
			+ "        \"id\": \"9beb1328-29a1-4501-9c94-352d0c1737f2\"\r\n"
			+ "    },\r\n"
			+ "    \"error_code\": \"00000\",\r\n"
			+ "    \"error_string\": \"success\"\r\n}" ;
	public static String showGroupDeepSuccess_repair = "{\r\n"
			+ "    \"content\": {\r\n"
			+ "        \"create_ns\": true,\r\n"
			+ "        \"id\": \"5cc95b20-e8f7-451d-bb96-0a4e44a24733\",\r\n"
			+ "        \"name\": \"repair\",\r\n"
			+ "        \"preempted\": false,\r\n"
			+ "        \"priority\": 2000,\r\n"
			+ "        \"role\": \"saas\",\r\n"
			+ "        \"site\": \"site1\",\r\n"
			+ "        \"tasks\": [\r\n"
			+ "            {\r\n"
			+ "                \"allocateds\": [\r\n"
			+ "                    {\r\n"
			+ "                        \"amd_gpu\": \"0\",\r\n"
			+ "                        \"cpu\": \"4\",\r\n"
			+ "                        \"id\": \"fa48564b-def8-41de-b39e-c952f45ce95c\",\r\n"
			+ "                        \"mem\": \"4Gi\",\r\n"
			+ "                        \"name\": \"postgres\",\r\n"
			+ "                        \"node_name\": \"ndc27-3221\",\r\n"
			+ "                        \"nvidia_gpu\": \"0\",\r\n"
			+ "                        \"site\": \"site1\",\r\n"
			+ "                        \"status\": \"Running\",\r\n"
			+ "                        \"task_id\": \"9cdd3345-f3b5-401e-b867-a330f565dcca\"\r\n"
			+ "                    }\r\n"
			+ "                ],\r\n"
			+ "                \"create_time\": \"2022-08-23T13:33:13Z\",\r\n"
			+ "                \"group_id\": \"d1840f34-ee28-4bad-a907-3a472205eb86\",\r\n"
			+ "                \"id\": \"9cdd3345-f3b5-401e-b867-a330f565dcca\",\r\n"
			+ "                \"kind\": \"deployment\",\r\n"
			+ "                \"name\": \"repair-front\",\r\n"
			+ "                \"namespace\": \"hogan-group-1\",\r\n"
			+ "                \"owner\": \"hogan\",\r\n"
			+ "                \"process_info\": \"Task [tensorflow-deploy-hogan] object [tensorflow-secret-hogan] kind [secret]: Create success\\r\\nTask [tensorflow-deploy-hogan] object [tensorflow-deploy-hogan] kind [deployment]: Create success\\r\\nTask [tensorflow-deploy-hogan] object [tensorflow-service-hogan] kind [service]: Create success\",\r\n"
			+ "                \"replica_set\": 1,\r\n"
			+ "                \"sch_time\": \"\",\r\n"
			+ "                \"site\": \"site1\",\r\n"
			+ "                \"start_time\": \"2022-09-30T09:10:26Z\",\r\n"
			+ "                \"status\": \"Running\",\r\n"
			+ "                \"yaml\": \"---\\r\\napiVersion: v1\\r\\nkind: Secret\\r\\nmetadata:\\r\\n  name: tensorflow-secret-hogan\\r\\ntype: Opaque\\r\\ndata:\\r\\n  password: aXRyaQ==\\r\\n  token: YXNkZnp4Y3Y=\\r\\n---\\r\\napiVersion: apps/v1\\r\\nkind: Deployment\\r\\nmetadata:\\r\\n  name: tensorflow-deploy-hogan\\r\\n  labels:\\r\\n    app: tensorflow\\r\\nspec:\\r\\n  replicas: 1\\r\\n  selector:\\r\\n    matchLabels:\\r\\n      app: tensorflow\\r\\n  template:\\r\\n    metadata:\\r\\n      labels:\\r\\n        app: tensorflow\\r\\n    spec:\\r\\n      containers:\\r\\n      - name: tensorflow\\r\\n        image: tensorflow:2.2.0-jupyter-no-gpu\\r\\n        imagePullPolicy: IfNotPresent\\r\\n        env:\\r\\n        - name: SSH_PASSWORD\\r\\n          valueFrom:\\r\\n            secretKeyRef:\\r\\n              name: tensorflow-secret-hogan\\r\\n              key: password\\r\\n        - name: JY_TOKEN\\r\\n          valueFrom:\\r\\n            secretKeyRef:\\r\\n              name: tensorflow-secret-hogan\\r\\n              key: token\\r\\n        ports:\\r\\n        - containerPort: 22\\r\\n        - containerPort: 8888\\r\\n        resources:\\r\\n          limits:\\r\\n            cpu: 4\\r\\n            memory: \\\"4Gi\\\"\\r\\n            nvidia.com/gpu: 0\\r\\n      dnsPolicy: Default\\r\\n---\\r\\napiVersion: v1\\r\\nkind: Service\\r\\nmetadata:\\r\\n  name: tensorflow-service-hogan\\r\\n  labels:\\r\\n    app: tensorflow\\r\\nspec:\\r\\n  ports:\\r\\n  - name: ssh\\r\\n    port: 22\\r\\n    nodePort: 30005\\r\\n  - name: jupyter\\r\\n    port: 8888\\r\\n  selector:\\r\\n    app: tensorflow\\r\\n  type: NodePort\"\r\n"
			+ "            }\r\n,"
			+ "            {\r\n"
			+ "                \"allocateds\": [\r\n"
			+ "                    {\r\n"
			+ "                        \"amd_gpu\": \"0\",\r\n"
			+ "                        \"cpu\": \"4\",\r\n"
			+ "                        \"id\": \"fa48564b-def8-41de-b39e-c952f45ce95c\",\r\n"
			+ "                        \"mem\": \"4Gi\",\r\n"
			+ "                        \"name\": \"postgres\",\r\n"
			+ "                        \"node_name\": \"ndc27-3221\",\r\n"
			+ "                        \"nvidia_gpu\": \"0\",\r\n"
			+ "                        \"site\": \"site1\",\r\n"
			+ "                        \"status\": \"Running\",\r\n"
			+ "                        \"task_id\": \"9cdd3345-f3b5-401e-b867-a330f565dcca\"\r\n"
			+ "                    }\r\n"
			+ "                ],\r\n"
			+ "                \"create_time\": \"2022-08-23T13:33:13Z\",\r\n"
			+ "                \"group_id\": \"d1840f34-ee28-4bad-a907-3a472205eb86\",\r\n"
			+ "                \"id\": \"9cdd3345-f3b5-401e-b867-a330f565dcca\",\r\n"
			+ "                \"kind\": \"deployment\",\r\n"
			+ "                \"name\": \"repair-back\",\r\n"
			+ "                \"namespace\": \"hogan-group-1\",\r\n"
			+ "                \"owner\": \"hogan\",\r\n"
			+ "                \"process_info\": \"Task [tensorflow-deploy-hogan] object [tensorflow-secret-hogan] kind [secret]: Create success\\r\\nTask [tensorflow-deploy-hogan] object [tensorflow-deploy-hogan] kind [deployment]: Create success\\r\\nTask [tensorflow-deploy-hogan] object [tensorflow-service-hogan] kind [service]: Create success\",\r\n"
			+ "                \"replica_set\": 1,\r\n"
			+ "                \"sch_time\": \"\",\r\n"
			+ "                \"site\": \"site1\",\r\n"
			+ "                \"start_time\": \"2022-09-30T09:10:26Z\",\r\n"
			+ "                \"status\": \"Running\",\r\n"
			+ "                \"yaml\": \"---\\r\\napiVersion: v1\\r\\nkind: Secret\\r\\nmetadata:\\r\\n  name: tensorflow-secret-hogan\\r\\ntype: Opaque\\r\\ndata:\\r\\n  password: aXRyaQ==\\r\\n  token: YXNkZnp4Y3Y=\\r\\n---\\r\\napiVersion: apps/v1\\r\\nkind: Deployment\\r\\nmetadata:\\r\\n  name: tensorflow-deploy-hogan\\r\\n  labels:\\r\\n    app: tensorflow\\r\\nspec:\\r\\n  replicas: 1\\r\\n  selector:\\r\\n    matchLabels:\\r\\n      app: tensorflow\\r\\n  template:\\r\\n    metadata:\\r\\n      labels:\\r\\n        app: tensorflow\\r\\n    spec:\\r\\n      containers:\\r\\n      - name: tensorflow\\r\\n        image: tensorflow:2.2.0-jupyter-no-gpu\\r\\n        imagePullPolicy: IfNotPresent\\r\\n        env:\\r\\n        - name: SSH_PASSWORD\\r\\n          valueFrom:\\r\\n            secretKeyRef:\\r\\n              name: tensorflow-secret-hogan\\r\\n              key: password\\r\\n        - name: JY_TOKEN\\r\\n          valueFrom:\\r\\n            secretKeyRef:\\r\\n              name: tensorflow-secret-hogan\\r\\n              key: token\\r\\n        ports:\\r\\n        - containerPort: 22\\r\\n        - containerPort: 8888\\r\\n        resources:\\r\\n          limits:\\r\\n            cpu: 4\\r\\n            memory: \\\"4Gi\\\"\\r\\n            nvidia.com/gpu: 0\\r\\n      dnsPolicy: Default\\r\\n---\\r\\napiVersion: v1\\r\\nkind: Service\\r\\nmetadata:\\r\\n  name: tensorflow-service-hogan\\r\\n  labels:\\r\\n    app: tensorflow\\r\\nspec:\\r\\n  ports:\\r\\n  - name: ssh\\r\\n    port: 22\\r\\n    nodePort: 30005\\r\\n  - name: jupyter\\r\\n    port: 8888\\r\\n  selector:\\r\\n    app: tensorflow\\r\\n  type: NodePort\"\r\n"
			+ "            }\r\n"
			+ "        ]\r\n"
			+ "    },\r\n"
			+ "    \"error_code\": \"00000\",\r\n"
			+ "    \"error_string\": \"success\"\r\n"
			+ "}";
	public static String showGroupDeepSuccess_ems = "{\r\n"
			+ "    \"content\": {\r\n"
			+ "        \"create_ns\": true,\r\n"
			+ "        \"id\": \"6fbb1016-82b7-4f54-b60c-88b27dd9b422\",\r\n"
			+ "        \"name\": \"ems\",\r\n"
			+ "        \"preempted\": false,\r\n"
			+ "        \"priority\": 3000,\r\n"
			+ "        \"role\": \"saas\",\r\n"
			+ "        \"site\": \"site1\",\r\n"
			+ "        \"tasks\": [\r\n"
			+ "            {\r\n"
			+ "                \"allocateds\": [\r\n"
			+ "                    {\r\n"
			+ "                        \"amd_gpu\": \"0\",\r\n"
			+ "                        \"cpu\": \"4\",\r\n"
			+ "                        \"id\": \"fa48564b-def8-41de-b39e-c952f45ce95c\",\r\n"
			+ "                        \"mem\": \"4Gi\",\r\n"
			+ "                        \"name\": \"postgres\",\r\n"
			+ "                        \"node_name\": \"ndc27-3221\",\r\n"
			+ "                        \"nvidia_gpu\": \"0\",\r\n"
			+ "                        \"site\": \"site1\",\r\n"
			+ "                        \"status\": \"Running\",\r\n"
			+ "                        \"task_id\": \"9cdd3345-f3b5-401e-b867-a330f565dcca\"\r\n"
			+ "                    }\r\n"
			+ "                ],\r\n"
			+ "                \"create_time\": \"2022-08-23T13:33:13Z\",\r\n"
			+ "                \"group_id\": \"d1840f34-ee28-4bad-a907-3a472205eb86\",\r\n"
			+ "                \"id\": \"9cdd3345-f3b5-401e-b867-a330f565dcca\",\r\n"
			+ "                \"kind\": \"deployment\",\r\n"
			+ "                \"name\": \"ems-front\",\r\n"
			+ "                \"namespace\": \"hogan-group-1\",\r\n"
			+ "                \"owner\": \"hogan\",\r\n"
			+ "                \"process_info\": \"Task [tensorflow-deploy-hogan] object [tensorflow-secret-hogan] kind [secret]: Create success\\r\\nTask [tensorflow-deploy-hogan] object [tensorflow-deploy-hogan] kind [deployment]: Create success\\r\\nTask [tensorflow-deploy-hogan] object [tensorflow-service-hogan] kind [service]: Create success\",\r\n"
			+ "                \"replica_set\": 1,\r\n"
			+ "                \"sch_time\": \"\",\r\n"
			+ "                \"site\": \"site1\",\r\n"
			+ "                \"start_time\": \"2022-09-30T09:10:26Z\",\r\n"
			+ "                \"status\": \"Running\",\r\n"
			+ "                \"yaml\": \"---\\r\\napiVersion: v1\\r\\nkind: Secret\\r\\nmetadata:\\r\\n  name: tensorflow-secret-hogan\\r\\ntype: Opaque\\r\\ndata:\\r\\n  password: aXRyaQ==\\r\\n  token: YXNkZnp4Y3Y=\\r\\n---\\r\\napiVersion: apps/v1\\r\\nkind: Deployment\\r\\nmetadata:\\r\\n  name: tensorflow-deploy-hogan\\r\\n  labels:\\r\\n    app: tensorflow\\r\\nspec:\\r\\n  replicas: 1\\r\\n  selector:\\r\\n    matchLabels:\\r\\n      app: tensorflow\\r\\n  template:\\r\\n    metadata:\\r\\n      labels:\\r\\n        app: tensorflow\\r\\n    spec:\\r\\n      containers:\\r\\n      - name: tensorflow\\r\\n        image: tensorflow:2.2.0-jupyter-no-gpu\\r\\n        imagePullPolicy: IfNotPresent\\r\\n        env:\\r\\n        - name: SSH_PASSWORD\\r\\n          valueFrom:\\r\\n            secretKeyRef:\\r\\n              name: tensorflow-secret-hogan\\r\\n              key: password\\r\\n        - name: JY_TOKEN\\r\\n          valueFrom:\\r\\n            secretKeyRef:\\r\\n              name: tensorflow-secret-hogan\\r\\n              key: token\\r\\n        ports:\\r\\n        - containerPort: 22\\r\\n        - containerPort: 8888\\r\\n        resources:\\r\\n          limits:\\r\\n            cpu: 4\\r\\n            memory: \\\"4Gi\\\"\\r\\n            nvidia.com/gpu: 0\\r\\n      dnsPolicy: Default\\r\\n---\\r\\napiVersion: v1\\r\\nkind: Service\\r\\nmetadata:\\r\\n  name: tensorflow-service-hogan\\r\\n  labels:\\r\\n    app: tensorflow\\r\\nspec:\\r\\n  ports:\\r\\n  - name: ssh\\r\\n    port: 22\\r\\n    nodePort: 30005\\r\\n  - name: jupyter\\r\\n    port: 8888\\r\\n  selector:\\r\\n    app: tensorflow\\r\\n  type: NodePort\"\r\n"
			+ "            }\r\n,"
			+ "            {\r\n"
			+ "                \"allocateds\": [\r\n"
			+ "                    {\r\n"
			+ "                        \"amd_gpu\": \"0\",\r\n"
			+ "                        \"cpu\": \"4\",\r\n"
			+ "                        \"id\": \"fa48564b-def8-41de-b39e-c952f45ce95c\",\r\n"
			+ "                        \"mem\": \"4Gi\",\r\n"
			+ "                        \"name\": \"postgres\",\r\n"
			+ "                        \"node_name\": \"ndc27-3221\",\r\n"
			+ "                        \"nvidia_gpu\": \"0\",\r\n"
			+ "                        \"site\": \"site1\",\r\n"
			+ "                        \"status\": \"Running\",\r\n"
			+ "                        \"task_id\": \"9cdd3345-f3b5-401e-b867-a330f565dcca\"\r\n"
			+ "                    }\r\n"
			+ "                ],\r\n"
			+ "                \"create_time\": \"2022-08-23T13:33:13Z\",\r\n"
			+ "                \"group_id\": \"d1840f34-ee28-4bad-a907-3a472205eb86\",\r\n"
			+ "                \"id\": \"9cdd3345-f3b5-401e-b867-a330f565dcca\",\r\n"
			+ "                \"kind\": \"deployment\",\r\n"
			+ "                \"name\": \"ems-back\",\r\n"
			+ "                \"namespace\": \"hogan-group-1\",\r\n"
			+ "                \"owner\": \"hogan\",\r\n"
			+ "                \"process_info\": \"Task [tensorflow-deploy-hogan] object [tensorflow-secret-hogan] kind [secret]: Create success\\r\\nTask [tensorflow-deploy-hogan] object [tensorflow-deploy-hogan] kind [deployment]: Create success\\r\\nTask [tensorflow-deploy-hogan] object [tensorflow-service-hogan] kind [service]: Create success\",\r\n"
			+ "                \"replica_set\": 1,\r\n"
			+ "                \"sch_time\": \"\",\r\n"
			+ "                \"site\": \"site1\",\r\n"
			+ "                \"start_time\": \"2022-09-30T09:10:26Z\",\r\n"
			+ "                \"status\": \"Running\",\r\n"
			+ "                \"yaml\": \"---\\r\\napiVersion: v1\\r\\nkind: Secret\\r\\nmetadata:\\r\\n  name: tensorflow-secret-hogan\\r\\ntype: Opaque\\r\\ndata:\\r\\n  password: aXRyaQ==\\r\\n  token: YXNkZnp4Y3Y=\\r\\n---\\r\\napiVersion: apps/v1\\r\\nkind: Deployment\\r\\nmetadata:\\r\\n  name: tensorflow-deploy-hogan\\r\\n  labels:\\r\\n    app: tensorflow\\r\\nspec:\\r\\n  replicas: 1\\r\\n  selector:\\r\\n    matchLabels:\\r\\n      app: tensorflow\\r\\n  template:\\r\\n    metadata:\\r\\n      labels:\\r\\n        app: tensorflow\\r\\n    spec:\\r\\n      containers:\\r\\n      - name: tensorflow\\r\\n        image: tensorflow:2.2.0-jupyter-no-gpu\\r\\n        imagePullPolicy: IfNotPresent\\r\\n        env:\\r\\n        - name: SSH_PASSWORD\\r\\n          valueFrom:\\r\\n            secretKeyRef:\\r\\n              name: tensorflow-secret-hogan\\r\\n              key: password\\r\\n        - name: JY_TOKEN\\r\\n          valueFrom:\\r\\n            secretKeyRef:\\r\\n              name: tensorflow-secret-hogan\\r\\n              key: token\\r\\n        ports:\\r\\n        - containerPort: 22\\r\\n        - containerPort: 8888\\r\\n        resources:\\r\\n          limits:\\r\\n            cpu: 4\\r\\n            memory: \\\"4Gi\\\"\\r\\n            nvidia.com/gpu: 0\\r\\n      dnsPolicy: Default\\r\\n---\\r\\napiVersion: v1\\r\\nkind: Service\\r\\nmetadata:\\r\\n  name: tensorflow-service-hogan\\r\\n  labels:\\r\\n    app: tensorflow\\r\\nspec:\\r\\n  ports:\\r\\n  - name: ssh\\r\\n    port: 22\\r\\n    nodePort: 30005\\r\\n  - name: jupyter\\r\\n    port: 8888\\r\\n  selector:\\r\\n    app: tensorflow\\r\\n  type: NodePort\"\r\n"
			+ "            }\r\n"
			+ "        ]\r\n"
			+ "    },\r\n"
			+ "    \"error_code\": \"00000\",\r\n"
			+ "    \"error_string\": \"success\"\r\n"
			+ "}";
	public static String showGroupDeepSuccess_bim_viewer = "{\r\n"
			+ "    \"content\": {\r\n"
			+ "        \"create_ns\": true,\r\n"
			+ "        \"id\": \"9482f447-b6ed-46ee-9268-54b70812196f\",\r\n"
			+ "        \"name\": \"bim-viewer\",\r\n"
			+ "        \"preempted\": false,\r\n"
			+ "        \"priority\": 4000,\r\n"
			+ "        \"role\": \"saas\",\r\n"
			+ "        \"site\": \"site1\",\r\n"
			+ "        \"tasks\": [\r\n"
			+ "            {\r\n"
			+ "                \"allocateds\": [\r\n"
			+ "                    {\r\n"
			+ "                        \"amd_gpu\": \"0\",\r\n"
			+ "                        \"cpu\": \"4\",\r\n"
			+ "                        \"id\": \"fa48564b-def8-41de-b39e-c952f45ce95c\",\r\n"
			+ "                        \"mem\": \"4Gi\",\r\n"
			+ "                        \"name\": \"postgres\",\r\n"
			+ "                        \"node_name\": \"ndc27-3221\",\r\n"
			+ "                        \"nvidia_gpu\": \"0\",\r\n"
			+ "                        \"site\": \"site1\",\r\n"
			+ "                        \"status\": \"Running\",\r\n"
			+ "                        \"task_id\": \"9cdd3345-f3b5-401e-b867-a330f565dcca\"\r\n"
			+ "                    }\r\n"
			+ "                ],\r\n"
			+ "                \"create_time\": \"2022-08-23T13:33:13Z\",\r\n"
			+ "                \"group_id\": \"d1840f34-ee28-4bad-a907-3a472205eb86\",\r\n"
			+ "                \"id\": \"9cdd3345-f3b5-401e-b867-a330f565dcca\",\r\n"
			+ "                \"kind\": \"deployment\",\r\n"
			+ "                \"name\": \"bim-viewer\",\r\n"
			+ "                \"namespace\": \"hogan-group-1\",\r\n"
			+ "                \"owner\": \"hogan\",\r\n"
			+ "                \"process_info\": \"Task [tensorflow-deploy-hogan] object [tensorflow-secret-hogan] kind [secret]: Create success\\r\\nTask [tensorflow-deploy-hogan] object [tensorflow-deploy-hogan] kind [deployment]: Create success\\r\\nTask [tensorflow-deploy-hogan] object [tensorflow-service-hogan] kind [service]: Create success\",\r\n"
			+ "                \"replica_set\": 1,\r\n"
			+ "                \"sch_time\": \"\",\r\n"
			+ "                \"site\": \"site1\",\r\n"
			+ "                \"start_time\": \"2022-09-30T09:10:26Z\",\r\n"
			+ "                \"status\": \"Running\",\r\n"
			+ "                \"yaml\": \"---\\r\\napiVersion: v1\\r\\nkind: Secret\\r\\nmetadata:\\r\\n  name: tensorflow-secret-hogan\\r\\ntype: Opaque\\r\\ndata:\\r\\n  password: aXRyaQ==\\r\\n  token: YXNkZnp4Y3Y=\\r\\n---\\r\\napiVersion: apps/v1\\r\\nkind: Deployment\\r\\nmetadata:\\r\\n  name: tensorflow-deploy-hogan\\r\\n  labels:\\r\\n    app: tensorflow\\r\\nspec:\\r\\n  replicas: 1\\r\\n  selector:\\r\\n    matchLabels:\\r\\n      app: tensorflow\\r\\n  template:\\r\\n    metadata:\\r\\n      labels:\\r\\n        app: tensorflow\\r\\n    spec:\\r\\n      containers:\\r\\n      - name: tensorflow\\r\\n        image: tensorflow:2.2.0-jupyter-no-gpu\\r\\n        imagePullPolicy: IfNotPresent\\r\\n        env:\\r\\n        - name: SSH_PASSWORD\\r\\n          valueFrom:\\r\\n            secretKeyRef:\\r\\n              name: tensorflow-secret-hogan\\r\\n              key: password\\r\\n        - name: JY_TOKEN\\r\\n          valueFrom:\\r\\n            secretKeyRef:\\r\\n              name: tensorflow-secret-hogan\\r\\n              key: token\\r\\n        ports:\\r\\n        - containerPort: 22\\r\\n        - containerPort: 8888\\r\\n        resources:\\r\\n          limits:\\r\\n            cpu: 4\\r\\n            memory: \\\"4Gi\\\"\\r\\n            nvidia.com/gpu: 0\\r\\n      dnsPolicy: Default\\r\\n---\\r\\napiVersion: v1\\r\\nkind: Service\\r\\nmetadata:\\r\\n  name: tensorflow-service-hogan\\r\\n  labels:\\r\\n    app: tensorflow\\r\\nspec:\\r\\n  ports:\\r\\n  - name: ssh\\r\\n    port: 22\\r\\n    nodePort: 30005\\r\\n  - name: jupyter\\r\\n    port: 8888\\r\\n  selector:\\r\\n    app: tensorflow\\r\\n  type: NodePort\"\r\n"
			+ "            }\r\n"
			+ "        ]\r\n"
			+ "    },\r\n"
			+ "    \"error_code\": \"00000\",\r\n"
			+ "    \"error_string\": \"success\"\r\n"
			+ "}";
	public static String showGroupDeepSuccess_postgres = "{\r\n"
			+ "    \"content\": {\r\n"
			+ "        \"create_ns\": true,\r\n"
			+ "        \"id\": \"9beb1328-29a1-4501-9c94-352d0c1737f2\",\r\n"
			+ "        \"name\": \"postgres\",\r\n"
			+ "        \"preempted\": false,\r\n"
			+ "        \"priority\": 5000,\r\n"
			+ "        \"role\": \"saas\",\r\n"
			+ "        \"site\": \"site1\",\r\n"
			+ "        \"tasks\": [\r\n"
			+ "            {\r\n"
			+ "                \"allocateds\": [\r\n"
			+ "                    {\r\n"
			+ "                        \"amd_gpu\": \"0\",\r\n"
			+ "                        \"cpu\": \"4\",\r\n"
			+ "                        \"id\": \"fa48564b-def8-41de-b39e-c952f45ce95c\",\r\n"
			+ "                        \"mem\": \"4Gi\",\r\n"
			+ "                        \"name\": \"postgres\",\r\n"
			+ "                        \"node_name\": \"ndc27-3221\",\r\n"
			+ "                        \"nvidia_gpu\": \"0\",\r\n"
			+ "                        \"site\": \"site1\",\r\n"
			+ "                        \"status\": \"Running\",\r\n"
			+ "                        \"task_id\": \"9cdd3345-f3b5-401e-b867-a330f565dcca\"\r\n"
			+ "                    }\r\n"
			+ "                ],\r\n"
			+ "                \"create_time\": \"2022-08-23T13:33:13Z\",\r\n"
			+ "                \"group_id\": \"d1840f34-ee28-4bad-a907-3a472205eb86\",\r\n"
			+ "                \"id\": \"9cdd3345-f3b5-401e-b867-a330f565dcca\",\r\n"
			+ "                \"kind\": \"deployment\",\r\n"
			+ "                \"name\": \"postgres\",\r\n"
			+ "                \"namespace\": \"hogan-group-1\",\r\n"
			+ "                \"owner\": \"hogan\",\r\n"
			+ "                \"process_info\": \"Task [tensorflow-deploy-hogan] object [tensorflow-secret-hogan] kind [secret]: Create success\\r\\nTask [tensorflow-deploy-hogan] object [tensorflow-deploy-hogan] kind [deployment]: Create success\\r\\nTask [tensorflow-deploy-hogan] object [tensorflow-service-hogan] kind [service]: Create success\",\r\n"
			+ "                \"replica_set\": 1,\r\n"
			+ "                \"sch_time\": \"\",\r\n"
			+ "                \"site\": \"site1\",\r\n"
			+ "                \"start_time\": \"2022-09-30T09:10:26Z\",\r\n"
			+ "                \"status\": \"Running\",\r\n"
			+ "                \"yaml\": \"---\\r\\napiVersion: v1\\r\\nkind: Secret\\r\\nmetadata:\\r\\n  name: tensorflow-secret-hogan\\r\\ntype: Opaque\\r\\ndata:\\r\\n  password: aXRyaQ==\\r\\n  token: YXNkZnp4Y3Y=\\r\\n---\\r\\napiVersion: apps/v1\\r\\nkind: Deployment\\r\\nmetadata:\\r\\n  name: tensorflow-deploy-hogan\\r\\n  labels:\\r\\n    app: tensorflow\\r\\nspec:\\r\\n  replicas: 1\\r\\n  selector:\\r\\n    matchLabels:\\r\\n      app: tensorflow\\r\\n  template:\\r\\n    metadata:\\r\\n      labels:\\r\\n        app: tensorflow\\r\\n    spec:\\r\\n      containers:\\r\\n      - name: tensorflow\\r\\n        image: tensorflow:2.2.0-jupyter-no-gpu\\r\\n        imagePullPolicy: IfNotPresent\\r\\n        env:\\r\\n        - name: SSH_PASSWORD\\r\\n          valueFrom:\\r\\n            secretKeyRef:\\r\\n              name: tensorflow-secret-hogan\\r\\n              key: password\\r\\n        - name: JY_TOKEN\\r\\n          valueFrom:\\r\\n            secretKeyRef:\\r\\n              name: tensorflow-secret-hogan\\r\\n              key: token\\r\\n        ports:\\r\\n        - containerPort: 22\\r\\n        - containerPort: 8888\\r\\n        resources:\\r\\n          limits:\\r\\n            cpu: 4\\r\\n            memory: \\\"4Gi\\\"\\r\\n            nvidia.com/gpu: 0\\r\\n      dnsPolicy: Default\\r\\n---\\r\\napiVersion: v1\\r\\nkind: Service\\r\\nmetadata:\\r\\n  name: tensorflow-service-hogan\\r\\n  labels:\\r\\n    app: tensorflow\\r\\nspec:\\r\\n  ports:\\r\\n  - name: ssh\\r\\n    port: 22\\r\\n    nodePort: 30005\\r\\n  - name: jupyter\\r\\n    port: 8888\\r\\n  selector:\\r\\n    app: tensorflow\\r\\n  type: NodePort\"\r\n"
			+ "            }\r\n"
			+ "        ]\r\n"
			+ "    },\r\n"
			+ "    \"error_code\": \"00000\",\r\n"
			+ "    \"error_string\": \"success\"\r\n"
			+ "}";
	public static String deleteGroupSuccess = "{\r\n"
			+ "    \"content\": {},\r\n"
			+ "    \"error_code\": \"00000\",\r\n"
			+ "    \"error_string\": \"success\"\r\n"
			+ "}";
}
